sudo: required
service: 
    - docker

before_install:
    - docker build -t angelspandjev/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true angelspandjev/react-test npm test

after_success:
    - docker build -t angelspandjev/multi-client ./client
    - docker build -t angelspandjev/multi-nginx ./nginx
    - docker build -t angelspandjev/multi-server ./server
    - docker build -t angelspandjev/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take images and push to docker hub
    - docker push angelspandjev/multi-client
    - docker push angelspandjev/multi-nginx
    - docker push angelspandjev/multi-server
    - docker push angelspandjev/multi-worker
